name: Clojure CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: DeLaGuardo/setup-clojure@10.3
      with:
        cli: 1.11.1.1323

    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.gitlibs
          ~/.m2
        key: ${{ runner.os }}-${{ hashFiles('deps.edn') }}

    - name: Run tests
      run: clojure -X:test
